name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pre-commit CI
        id: install
        run: |
            python3 -m venv ~/pre-commit
            ~/pre-commit/bin/pip install --upgrade pip setuptools
            ~/pre-commit/bin/pip install pre-commit
            echo "envhash=$({ python3 --version && cat .github/pre-commit/config.yaml; } | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.install.outputs.envhash }}
      - name: Run pre-commit CI
        run: ~/pre-commit/bin/pre-commit run -c .github/pre-commit/config.yaml --show-diff-on-failure --color=always --all-files
